### ISSUE TITLE
关于头文件的问题

### ISSUE THREAD

**Issue by xiaonian233** [DragonQuestHero/CSKZ-AutoBhopJump#1]
您好作者，不知道您能否提供项目相关的头文件呢？

**Comment by DragonQuestHero** [comment]
R3不需要那个头文件也可以 当初依赖了但是修改了代码 没有用上那部分代码

**Comment by xiaonian233** [comment]
好像不太行，删除以后，main里面错误就全出来了，我有那个wdk的环境

**Comment by DragonQuestHero** [comment]
哦哦 环0的你需要自己写一下IOCTL 我怕我把自己的放出来被恶意利用以后把我自己的号也封掉了

**Comment by xiaonian233** [comment]
好嘞谢谢

**Comment by xiaonian233** [comment]
老哥过这么久，还打扰您不太好意思，这个表示能力真的达不到，不知道您是否可以将驱动私发一下，不会外传。

**Comment by DragonQuestHero** [comment]
很久没上github了 回头你加我吧

**Comment by xiaonian233** [comment]
邮箱发送了
